Walt java
redjen/FoodMood pull request #23
Opened 2017-10-22 15:45 UTC by lmdgr34

Login View

2017-10-22 17:57 UTC, lmdgr34 commented
Mood View and controllers part 1

2017-10-22 18:43 UTC, redjen requested changes
Looking good, the only thing that needs to change are the variable names I noted because Java needs to have that in order to work. Alyson's working on the Account classes and might have changes for those two.

2017-10-22 18:43 UTC, redjen commented on src/app/MoodViewController.java
> +    //mood slider for excited
The variable names need to match the associated fx:id, like moodAngry etc.

2017-10-22 23:43 UTC, redjen requested changes
This looks good but failed to launch for me with this: "Caused by: java.lang.IllegalArgumentException: Can not set javafx.scene.control.PasswordField field app.LoginController.password to javafx.scene.control.TextField"

Can you change the document loaded to the login view in App.java, then take a look at this? (we need that anyway) I think it's because the password field is PasswordFIeld in the controller but TextField in the view. You'll actually need to run the app to get the exception and logs. This isn't something that the compiler will catch, so it won't get flagged in NetBeans.

Once that's fixed this should be good to go.

2017-10-22 23:49 UTC, lmdgr34 commented
changes made

2017-10-23 00:59 UTC, redjen commented
It complained about one more thing. :( The controller needs to have the handler for the button since it's defined in the view.

    @FXML
    public void loginButtonHandler(ActionEvent event) {

    }

2017-10-23 02:14 UTC, redjen approved these changes
The next task I have depends on this, so I'm just going to approve and merge it so I can get started. It's a little change so I'll just make it.

2017-10-23 02:14 UTC, merged